services:
  database:
    restart: always
    image: postgres:alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file: 
      - ./config/.env.prod

  redis:
    restart: always
    image: redis:alpine

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn wsgi:application -w 12 --bind 0.0.0.0:8000
    volumes: 
      - ./:/usr/src/app
    expose:
      - 8000
    env_file: 
      - ./config/.env.prod
    depends_on: 
      - database
      - redis

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A helios worker -l INFO
    volumes: 
      - ./:/usr/src/app
    env_file: 
      - ./config/.env.prod
    depends_on: 
      - database
      - redis

  nginx:
    image: nginx:alpine
    volumes: 
      - ./:/usr/src/app
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - web

volumes:
  postgres_data: